const APP_VERSION='1.2.1';
const KEY='zalves-data-v2';
const EXERCISES=window.ZALVES_EXERCISES||[];
const localDateKey=date=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`};
const today=localDateKey(new Date());
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
let activeFilter=null;
let selectedExercise=null;
let viewerExercise=null;
let viewerScale=1;
let viewerX=0;
let viewerY=0;
let dragState=null;
const viewerPointers=new Map();
let pinchStartDistance=0;
let pinchStartScale=1;

function splitMuscles(value=''){
  const text=String(value||'').trim();
  if(!text)return [];
  const parts=[];let part='';let depth=0;
  for(const char of text){
    if(char==='(')depth++;
    if(char===')'&&depth>0)depth--;
    if(char===','&&depth===0){if(part.trim())parts.push(part.trim());part='';}else part+=char;
  }
  if(part.trim())parts.push(part.trim());
  return [...new Set(parts.filter(Boolean))];
}
function parseMuscles(value){
  if(Array.isArray(value))return [...new Set(value.flatMap(item=>splitMuscles(item)))];
  if(typeof value==='string'){
    try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parseMuscles(parsed)}catch(error){}
    return splitMuscles(value);
  }
  return [];
}
function workoutMuscles(workout){return parseMuscles(workout?.muscles?.length?workout.muscles:workout?.title)}
function esc(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function fmtDate(date){return new Date(date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}
function fullDate(date){return date.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}
function greeting(){const hour=new Date().getHours();return hour<5?'Доброй ночи':hour<12?'Доброе утро':hour<18?'Добрый день':'Добрый вечер'}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2200)}
function loadData(){let stored=null;try{stored=JSON.parse(localStorage.getItem(KEY)||'null')}catch(error){}if(!stored){try{stored=JSON.parse(localStorage.getItem('zalves-data-v1')||'null')}catch(error){}}const result=stored||{workouts:[],measurements:[],profile:{name:'',goal:'Набор мышц'}};result.workouts=(result.workouts||[]).map(workout=>({...workout,id:workout.id||uid(),muscles:workoutMuscles(workout)}));result.measurements=result.measurements||[];result.profile=result.profile||{name:'',goal:'Набор мышц'};localStorage.setItem(KEY,JSON.stringify(result));return result}
let data=loadData();
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function closeModal(id){const node=$('#'+id);if(node)node.classList.remove('open')}
function closeModals(){$$('.modal-backdrop').forEach(node=>node.classList.remove('open'));selectedExercise=null;viewerExercise=null}
function navigate(id){$$('.view').forEach(view=>view.classList.toggle('active',view.id===id));$$('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===id));window.scrollTo(0,0)}
function lineChart(values,color='var(--accent)'){if(!values.length)return '<div class="empty">Недостаточно данных для графика</div>';const width=500,height=165,min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((value,index)=>`${(index/(values.length-1||1))*width},${height-15-((value-min)/range)*(height-30)}`).join(' ');return `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none"><polyline points="${points}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${values.map((value,index)=>`<circle cx="${(index/(values.length-1||1))*width}" cy="${height-15-((value-min)/range)*(height-30)}" r="4" fill="${color}"/>`).join('')}</svg>`}
function renderWorkoutList(workouts){const visible=activeFilter?workouts.filter(workout=>workout.exercise===activeFilter||workoutMuscles(workout).includes(activeFilter)):workouts;$('#workoutList').innerHTML=visible.length?visible.map(workout=>{const muscles=workoutMuscles(workout).map(muscle=>`<span class="inline-tag">${esc(muscle)}</span>`).join('');return `<article class="record"><div class="record-top"><div><strong>${esc(workout.exercise||workout.title||'Упражнение')}</strong><small>${fmtDate(workout.date)}${workout.title?' · группа мышц':''}</small></div><span class="metric">${esc(workout.weight)} кг</span></div><div class="record-muscles">${muscles}</div><p>${esc(workout.sets)} подхода × ${esc(workout.reps)} повторений${workout.note?' · '+esc(workout.note):''}</p><div class="record-actions"><button data-edit="${workout.id}">Изменить</button><button data-delete="${workout.id}">Удалить</button></div></article>`}).join(''):'<div class="empty">'+(activeFilter?'По этому тегу тренировок нет.':'Тренировок пока нет.<br>Нажмите «＋», чтобы добавить первую.')+'</div>'}
function renderCatalog(){const grid=$('#exerciseGrid');if(!grid)return;if(!EXERCISES.length){grid.innerHTML='<div class="empty">Каталог упражнений пока пуст.</div>';return}grid.innerHTML=EXERCISES.map((exercise,index)=>`<article class="exercise-card"><div class="exercise-image-wrap"><img src="${esc(exercise.image)}" alt="${esc(exercise.name)}" loading="lazy"><span class="image-fallback">Добавьте ${esc(exercise.image)}</span><span class="exercise-number">${String(index+1).padStart(2,'0')}</span></div><div class="exercise-card-body"><h3>${esc(exercise.name)}</h3><div class="exercise-muscles">${exercise.muscles.map(muscle=>`<span>${esc(muscle)}</span>`).join('')}</div><div class="exercise-card-actions"><button type="button" data-exercise-select="${esc(exercise.id)}">Выбрать</button><button type="button" class="secondary" data-exercise-open="${esc(exercise.id)}">Открыть</button></div></div></article>`).join('');grid.querySelectorAll('img').forEach(image=>image.addEventListener('error',()=>image.closest('.exercise-image-wrap')?.classList.add('image-missing'),{once:true}))}
function renderQuickTags(muscles,exercises){$('#muscleTags').innerHTML=muscles.map(muscle=>`<option value="${esc(muscle)}">`).join('');$('#exerciseTags').innerHTML=exercises.map(exercise=>`<option value="${esc(exercise)}">`).join('');$('#muscleQuickTags').innerHTML=muscles.map(muscle=>`<button type="button" class="form-tag" data-fill="title" data-value="${esc(muscle)}">${esc(muscle)}</button>`).join('');$('#exerciseQuickTags').innerHTML=exercises.map(exercise=>`<button type="button" class="form-tag" data-fill="exercise" data-value="${esc(exercise)}">${esc(exercise)}</button>`).join('')}
function render(){const measurements=[...data.measurements].sort((a,b)=>String(a.date).localeCompare(String(b.date)));const workouts=[...data.workouts].sort((a,b)=>String(b.date).localeCompare(String(a.date)));const last=measurements.at(-1);const volume=data.workouts.reduce((sum,workout)=>sum+(+workout.weight||0)*(+workout.sets||0)*(+workout.reps||0),0);$('#todayDate').textContent=`Сегодня · ${fullDate(new Date())}`;$('#dashWeight').textContent=last?.weight||'—';$('#dashChest').textContent=last?.chest||'—';$('#dashWorkouts').textContent=data.workouts.length;$('#dashVolume').textContent=volume.toLocaleString('ru-RU');$('#dashWorkout').textContent=workouts[0]?.exercise||workouts[0]?.title||'Пока нет записей';$('#dashWorkoutMeta').textContent=workouts[0]?`${fmtDate(workouts[0].date)} · ${workouts[0].weight} кг`:'Создайте тренировку в разделе «Зал»';$('#streakText').textContent=data.profile.name?`${greeting()}, ${data.profile.name}`:`${greeting()} — добавьте первую запись`;
  const savedMuscles=[...new Set(data.workouts.flatMap(workout=>workoutMuscles(workout)))].filter(Boolean);const savedExercises=[...new Set(data.workouts.map(workout=>workout.exercise).filter(Boolean))];const catalogMuscles=[...new Set(EXERCISES.flatMap(exercise=>exercise.muscles))].filter(Boolean);const catalogExercises=[...new Set(EXERCISES.map(exercise=>exercise.name))].filter(Boolean);const muscles=[...new Set([...savedMuscles,...catalogMuscles])];const exercises=[...new Set([...savedExercises,...catalogExercises])];$('#filterCaption').hidden=!activeFilter;if(activeFilter)$('#activeFilter').textContent=activeFilter;$('#tagBar').innerHTML=[...savedMuscles.map(muscle=>({value:muscle,label:`Группа: ${muscle}`})),...savedExercises.map(exercise=>({value:exercise,label:`Упражнение: ${exercise}`}))].map(tag=>`<button type="button" class="tag ${activeFilter===tag.value?'selected':''}" data-filter="${esc(tag.value)}">${esc(tag.label)}</button>`).join('');renderWorkoutList(workouts);$('#measurementList').innerHTML=measurements.slice().reverse().map(measurement=>`<article class="record"><div class="record-top"><div><strong>${fmtDate(measurement.date)}</strong><small>Замер тела</small></div><span class="metric">${measurement.weight?esc(measurement.weight)+' кг':''}</span></div><p>${[['Грудь',measurement.chest],['Талия',measurement.waist],['Бицепс',measurement.arm]].filter(item=>item[1]).map(item=>item[0]+': '+esc(item[1])+' см').join(' · ')||'Только заметка'}${measurement.note?' · '+esc(measurement.note):''}</p></article>`).join('')||'<div class="empty">Добавьте первый замер тела.</div>';renderQuickTags(muscles,exercises);renderCatalog();renderChart();renderWeek();renderFullStats();$('#profileName').value=data.profile.name;$('#profileGoal').value=data.profile.goal}
function renderFullStats(){const workouts=data.workouts;const volume=workouts.reduce((sum,workout)=>sum+(+workout.weight||0)*(+workout.sets||0)*(+workout.reps||0),0);const best=workouts.reduce((max,workout)=>Math.max(max,+workout.weight||0),0);const days=new Set(workouts.map(workout=>workout.date)).size;$('#fullStats').innerHTML=`<article class="stat-card"><span>Тренировочных дней</span><strong>${days}</strong><small>уникальных дат</small></article><article class="stat-card"><span>Лучший вес</span><strong>${best}</strong><small>кг</small></article><article class="stat-card"><span>Всего подходов</span><strong>${workouts.reduce((sum,workout)=>sum+(+workout.sets||0),0)}</strong><small>подходов</small></article><article class="stat-card"><span>Общий объём</span><strong>${volume.toLocaleString('ru-RU')}</strong><small>кг × повторы</small></article>`}
function renderChart(type='weight'){const measurements=[...data.measurements].sort((a,b)=>String(a.date).localeCompare(String(b.date)));const values=type==='body'?measurements.map(item=>+item.chest).filter(Boolean):type==='lifts'?[...data.workouts].sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(item=>+item.weight):measurements.map(item=>+item.weight).filter(Boolean);$('#chartLabel').textContent=type==='body'?'Объём груди, см':type==='lifts'?'Рабочий вес, кг':'Вес тела, кг';$('#chartValue').textContent=values.at(-1)||'—';$('#chartTrend').textContent=values.length>1?(values.at(-1)-values[0]>=0?'↗ Рост':'↘ Снижение'):'Нет данных';$('#largeChart').innerHTML=lineChart(values,type==='body'?'var(--purple)':'var(--accent)')}
function renderWeek(){const days=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const now=new Date();const start=new Date(now);start.setDate(now.getDate()-((now.getDay()+6)%7));$('#weekChart').innerHTML=days.map((day,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);const key=localDateKey(date);const done=data.workouts.some(workout=>workout.date===key);return `<div class="day-bar"><div class="bar ${done?'done':''}" style="--h:${done?'62px':'22px'}"></div>${day}</div>`}).join('')}
function showSelectedExercise(exercise){const summary=$('#selectedExerciseSummary');if(!exercise){summary.hidden=true;return}$('#selectedExerciseName').textContent=exercise.name;const image=$('#selectedExerciseImage');image.src=exercise.image;image.alt=exercise.name;image.onerror=()=>{image.style.visibility='hidden'};summary.hidden=false}
function chooseExercise(exercise){const form=$('#workoutForm');form.elements.exerciseId.value=exercise.id;form.elements.exercise.value=exercise.name;form.elements.title.value=exercise.muscles.join(', ');form.elements.muscles.value=JSON.stringify(exercise.muscles);selectedExercise=exercise;showSelectedExercise(exercise);closeModal('exercisePickerModal');closeModal('exerciseViewerModal');toast('Упражнение и группы мышц подставлены')}
function openViewer(id){const exercise=EXERCISES.find(item=>item.id===id);if(!exercise)return;viewerExercise=exercise;$('#exerciseViewerImage').src=exercise.image;$('#exerciseViewerImage').alt=exercise.name;$('#exerciseViewerTitle').textContent=exercise.name;$('#exerciseViewerMuscles').innerHTML=exercise.muscles.map(muscle=>`<span class="inline-tag">${esc(muscle)}</span>`).join('');resetViewerZoom();$('#exerciseViewerModal').classList.add('open')}
function applyViewerTransform(){const image=$('#exerciseViewerImage');image.style.transform=`translate(${viewerX}px, ${viewerY}px) scale(${viewerScale})`;$('#zoomReset').textContent=`${Math.round(viewerScale*100)}%`}
function setViewerZoom(scale){viewerScale=Math.max(1,Math.min(4,scale));if(viewerScale===1){viewerX=0;viewerY=0}applyViewerTransform()}
function resetViewerZoom(){viewerScale=1;viewerX=0;viewerY=0;applyViewerTransform()}
function openWorkoutModal(item){const form=$('#workoutForm');form.reset();form.elements.date.value=item?.date||today;form.elements.id.value=item?.id||'';form.elements.exerciseId.value=item?.exerciseId||'';form.elements.muscles.value=JSON.stringify(workoutMuscles(item));form.elements.title.value=item?.title||'';form.elements.exercise.value=item?.exercise||'';form.elements.weight.value=item?.weight||'';form.elements.sets.value=item?.sets||3;form.elements.reps.value=item?.reps||10;form.elements.note.value=item?.note||'';$('#workoutModalEyebrow').textContent=item?'РЕДАКТИРОВАНИЕ':'НОВАЯ ЗАПИСЬ';$('#workoutModalTitle').textContent=item?'Изменить тренировку':'Тренировка';const catalogExercise=EXERCISES.find(exercise=>exercise.id===item?.exerciseId)||EXERCISES.find(exercise=>exercise.name===item?.exercise);selectedExercise=catalogExercise||null;showSelectedExercise(catalogExercise);$('#workoutModal').classList.add('open')}
function bindViewerDragging(){const stage=$('#exerciseZoomStage');const distance=()=>{const points=[...viewerPointers.values()];if(points.length<2)return 0;return Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y)};stage.addEventListener('pointerdown',event=>{viewerPointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(viewerPointers.size===2){pinchStartDistance=distance();pinchStartScale=viewerScale;dragState=null}else if(viewerScale>1){dragState={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,originX:viewerX,originY:viewerY};stage.setPointerCapture?.(event.pointerId)}});stage.addEventListener('pointermove',event=>{if(!viewerPointers.has(event.pointerId))return;viewerPointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(viewerPointers.size>=2&&pinchStartDistance){setViewerZoom(pinchStartScale*distance()/pinchStartDistance);return}if(!dragState||dragState.pointerId!==event.pointerId)return;viewerX=dragState.originX+event.clientX-dragState.startX;viewerY=dragState.originY+event.clientY-dragState.startY;applyViewerTransform()});const release=event=>{viewerPointers.delete(event.pointerId);if(viewerPointers.size<2)pinchStartDistance=0;dragState=null};stage.addEventListener('pointerup',release);stage.addEventListener('pointercancel',release);stage.addEventListener('wheel',event=>{event.preventDefault();setViewerZoom(viewerScale+(event.deltaY<0?.25:-.25))},{passive:false})}
$$('[data-view]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.view)));
$$('[data-modal]').forEach(button=>button.addEventListener('click',()=>button.dataset.modal==='workoutModal'?openWorkoutModal():openGenericModal(button.dataset.modal)));
function openGenericModal(id){const modal=$('#'+id);const form=modal?.querySelector('form');if(form?.elements.date)form.elements.date.value=today;modal?.classList.add('open')}
$$('.close-modal').forEach(button=>button.addEventListener('click',closeModals));
$$('.modal-backdrop').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)closeModals()}));
$$('.tab').forEach(button=>button.addEventListener('click',()=>{$$('.tab').forEach(tab=>tab.classList.remove('active'));button.classList.add('active');renderChart(button.dataset.chart)}));
$('#openExercisePicker').addEventListener('click',()=>{$('#exercisePickerModal').classList.add('open');renderCatalog()});
$('#exerciseGrid').addEventListener('click',event=>{const select=event.target.closest('[data-exercise-select]');const open=event.target.closest('[data-exercise-open]');if(select){const exercise=EXERCISES.find(item=>item.id===select.dataset.exerciseSelect);if(exercise)chooseExercise(exercise)}else if(open)openViewer(open.dataset.exerciseOpen)});
$('#workoutForm').addEventListener('click',event=>{const fill=event.target.closest('[data-fill]');if(fill){const field=$(`#workoutForm [name="${fill.dataset.fill}"]`);field.value=fill.dataset.value;if(fill.dataset.fill==='title')$('#workoutForm').elements.muscles.value=JSON.stringify(splitMuscles(fill.dataset.value))}});
$('#workoutList').addEventListener('click',event=>{const edit=event.target.closest('[data-edit]');const remove=event.target.closest('[data-delete]');if(edit){openWorkoutModal(data.workouts.find(workout=>workout.id===edit.dataset.edit))}if(remove&&confirm('Удалить эту тренировку?')){data.workouts=data.workouts.filter(workout=>workout.id!==remove.dataset.delete);save();toast('Тренировка удалена')}});
$('#tagBar').addEventListener('click',event=>{const tag=event.target.closest('[data-filter]');if(tag){activeFilter=activeFilter===tag.dataset.filter?null:tag.dataset.filter;render()}});
$('#clearFilter').addEventListener('click',()=>{activeFilter=null;render()});
$('#clearSelectedExercise').addEventListener('click',()=>{selectedExercise=null;$('#workoutForm').elements.exerciseId.value='';$('#workoutForm').elements.muscles.value='';$('#selectedExerciseSummary').hidden=true});
$('#viewerChoose').addEventListener('click',()=>{if(viewerExercise)chooseExercise(viewerExercise)});
$('#zoomIn').addEventListener('click',()=>setViewerZoom(viewerScale+.25));$('#zoomOut').addEventListener('click',()=>setViewerZoom(viewerScale-.25));$('#zoomReset').addEventListener('click',resetViewerZoom);bindViewerDragging();
$('#workoutForm').addEventListener('submit',event=>{event.preventDefault();const raw=Object.fromEntries(new FormData(event.target));const catalogExercise=EXERCISES.find(exercise=>exercise.id===raw.exerciseId&&exercise.name===raw.exercise);const muscles=catalogExercise?catalogExercise.muscles:parseMuscles(raw.title);const item={...raw,id:raw.id||uid(),muscles,title:muscles.join(', ')};const index=data.workouts.findIndex(workout=>workout.id===item.id);if(index<0)data.workouts.push(item);else data.workouts[index]=item;save();closeModals();event.target.reset();toast(index<0?'Тренировка сохранена':'Тренировка изменена')});
$('#measurementForm').addEventListener('submit',event=>{event.preventDefault();const item=Object.fromEntries(new FormData(event.target));Object.keys(item).forEach(key=>{if(!item[key])delete item[key]});data.measurements.push(item);save();closeModals();event.target.reset();toast('Замер сохранён')});
$('#saveProfile').addEventListener('click',()=>{data.profile={name:$('#profileName').value.trim(),goal:$('#profileGoal').value};save();toast('Профиль сохранён')});
$('#exportData').addEventListener('click',()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.download='zalves-backup.json';link.click()});
$('#clearData').addEventListener('click',()=>{if(confirm('Удалить все тренировки и замеры?')){data={workouts:[],measurements:[],profile:data.profile};save();toast('Данные удалены')}});
let deferred;const isStandalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
function hideInstall(){deferred=null;$('#installBanner').hidden=true;$('#installBtn').hidden=true;localStorage.setItem('zalves-installed','1')}
function showInstall(){if(isStandalone||localStorage.getItem('zalves-installed')==='1'){hideInstall();return}$('#installBanner').hidden=false;$('#installHint').textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?'Safari: Поделиться → На экран «Домой»':'Быстрый доступ и работа без интернета'}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferred=event;showInstall();$('#installBtn').hidden=false});
async function install(){if(deferred){deferred.prompt();const choice=await deferred.userChoice;if(choice?.outcome==='accepted'||isStandalone)hideInstall();else toast('Установку можно повторить позже')}else if(/iphone|ipad|ipod/i.test(navigator.userAgent))toast('Откройте Поделиться → На экран «Домой»')}
$('#bannerInstall').addEventListener('click',install);$('#installBtn').addEventListener('click',install);$('#closeInstall').addEventListener('click',()=>$('#installBanner').hidden=true);
$('#appVersion').textContent='v'+APP_VERSION;$('#settingsVersion').textContent=APP_VERSION;
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v='+APP_VERSION);
render();setTimeout(showInstall,700);
